services:
  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=talpets
      - POSTGRES_PASSWORD=talpets
    ports:
      - '5432:5432' # 5432 is postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data